services:
    _defaults:
        autowire: true
        autoconfigure: true

    OpcodingAADBundle\Security\AzureAuthenticator:
        arguments:
            - '@KnpU\OAuth2ClientBundle\Client\ClientRegistry'

    OpcodingAADBundle\Security\AzureUserProvider:
        arguments:

    OpcodingAADBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
